package net.dev.art.core.utils;

import org.bukkit.Material;

public class ArtTradutor {

	public static String translate(Material m) {
		switch(m) {
		case ACACIA_DOOR:
			return "Porta de acacia";
		case ACACIA_FENCE:
			return "Cerca de acacia";
		case ACACIA_FENCE_GATE:
			return "Portinhola de acacia";
		case ACACIA_STAIRS:
			return "Escada de acacia";
		case ACTIVATOR_RAIL:
			return "Trilho ativador";
		case ANVIL:
			return "Bigorna";
		case APPLE:
			return "Maça";
		case ARMOR_STAND:
			return "Espositor de Armaduras";
		case ARROW:
			return "Flechas";
		case BAKED_POTATO:
			return "Batata assada";
		case BANNER:
			return "Estandarte";
		case BARRIER:
			return "Barrera";
		case BEACON:
			return "Bacon";
		case BED:
			return "Cama";
		case BEDROCK:
			return "Rocha matriz";
		case BIRCH_DOOR:
			return "Porta de eucalipto";
		case BIRCH_FENCE:
			return "Cerca de eucalipto";
		case BIRCH_FENCE_GATE:
			return "Portinhola de eucalipto";
		case BIRCH_WOOD_STAIRS:
			return "Escada de eucalipto";
		case BLAZE_POWDER:
			return "Pó de blaze";
		case BLAZE_ROD:
			return "Vara de blaze";
		case BOAT:
			return "Barco";
		case BONE:
			return "Osso";
		case BOOK:
			return "Livro";
		case BOOKSHELF:
			return "Estante de livros";
		case BOOK_AND_QUILL:
			return "Livro com pena";
		case BOW:
			return "Arco";
		case BOWL:
			return "";
		case BREAD:
			return "";
		case BREWING_STAND:
			return "";
		case BREWING_STAND_ITEM:
			return "";
		case BRICK:
			return "";
		case BRICK_STAIRS:
			return "";
		case BROWN_MUSHROOM:
			return "";
		case BUCKET:
			return "";
		case BURNING_FURNACE:
			return "";
		case CACTUS:
			return "";
		case CAKE:
			return "";
		case CAKE_BLOCK:
			return "";
		case CARPET:
			return "";
		case CARROT:
			return "";
		case CARROT_ITEM:
			return "";
		case CARROT_STICK:
			return "";
		case CAULDRON:
			return "";
		case CAULDRON_ITEM:
			return "";
		case CHAINMAIL_BOOTS:
			return "";
		case CHAINMAIL_CHESTPLATE:
			return "";
		case CHAINMAIL_HELMET:
			return "";
		case CHAINMAIL_LEGGINGS:
			return "";
		case CHEST:
			return "";
		case CLAY:
			return "";
		case CLAY_BALL:
			return "";
		case CLAY_BRICK:
			return "";
		case COAL:
			return "";
		case COAL_BLOCK:
			return "";
		case COAL_ORE:
			return "";
		case COBBLESTONE:
			return "";
		case COBBLESTONE_STAIRS:
			return "";
		case COBBLE_WALL:
			return "";
		case COCOA:
			return "";
		case COMMAND:
			return "";
		case COMMAND_MINECART:
			return "";
		case COMPASS:
			return "";
		case COOKED_BEEF:
			return "";
		case COOKED_CHICKEN:
			return "";
		case COOKED_FISH:
			return "";
		case COOKED_MUTTON:
			return "";
		case COOKED_RABBIT:
			return "";
		case COOKIE:
			return "";
		case CROPS:
			return "";
		case DARK_OAK_DOOR:
			return "";
		case DARK_OAK_DOOR_ITEM:
			return "";
		case DARK_OAK_FENCE:
			return "";
		case DARK_OAK_FENCE_GATE:
			return "";
		case DARK_OAK_STAIRS:
			return "";
		case DAYLIGHT_DETECTOR:
			return "";
		case DAYLIGHT_DETECTOR_INVERTED:
			return "";
		case DEAD_BUSH:
			return "";
		case DETECTOR_RAIL:
			return "";
		case DIAMOND:
			return "";
		case DIAMOND_AXE:
			return "";
		case DIAMOND_BARDING:
			return "";
		case DIAMOND_BLOCK:
			return "";
		case DIAMOND_BOOTS:
			return "";
		case DIAMOND_CHESTPLATE:
			return "";
		case DIAMOND_HELMET:
			return "";
		case DIAMOND_HOE:
			return "";
		case DIAMOND_LEGGINGS:
			return "";
		case DIAMOND_ORE:
			return "";
		case DIAMOND_PICKAXE:
			return "";
		case DIAMOND_SPADE:
			return "";
		case DIAMOND_SWORD:
			return "";
		case DIODE:
			return "";
		case DIODE_BLOCK_OFF:
			return "";
		case DIODE_BLOCK_ON:
			return "";
		case DIRT:
			return "";
		case DISPENSER:
			return "";
		case DOUBLE_PLANT:
			return "";
		case DOUBLE_STEP:
			return "";
		case DOUBLE_STONE_SLAB2:
			return "";
		case DRAGON_EGG:
			return "";
		case DROPPER:
			return "";
		case EGG:
			return "";
		case EMERALD:
			return "";
		case EMERALD_BLOCK:
			return "";
		case EMERALD_ORE:
			return "";
		case EMPTY_MAP:
			return "";
		case ENCHANTED_BOOK:
			return "";
		case ENCHANTMENT_TABLE:
			return "";
		case ENDER_CHEST:
			return "";
		case ENDER_PEARL:
			return "";
		case ENDER_PORTAL:
			return "";
		case ENDER_PORTAL_FRAME:
			return "";
		case ENDER_STONE:
			return "";
		case EXPLOSIVE_MINECART:
			return "";
		case EXP_BOTTLE:
			return "";
		case EYE_OF_ENDER:
			return "";
		case FEATHER:
			return "";
		case FENCE:
			return "";
		case FENCE_GATE:
			return "";
		case FERMENTED_SPIDER_EYE:
			return "";
		case FIRE:
			return "";
		case FIREBALL:
			return "";
		case FIREWORK:
			return "";
		case FIREWORK_CHARGE:
			return "";
		case FISHING_ROD:
			return "";
		case FLINT:
			return "";
		case FLINT_AND_STEEL:
			return "";
		case FLOWER_POT:
			return "";
		case FLOWER_POT_ITEM:
			return "";
		case FURNACE:
			return "";
		case GHAST_TEAR:
			return "";
		case GLASS:
			return "";
		case GLASS_BOTTLE:
			return "";
		case GLOWING_REDSTONE_ORE:
			return "";
		case GLOWSTONE:
			return "";
		case GLOWSTONE_DUST:
			return "";
		case GOLDEN_APPLE:
			return "";
		case GOLDEN_CARROT:
			return "";
		case GOLD_AXE:
			return "";
		case GOLD_BARDING:
			return "";
		case GOLD_BLOCK:
			return "";
		case GOLD_BOOTS:
			return "";
		case GOLD_CHESTPLATE:
			return "";
		case GOLD_HELMET:
			return "";
		case GOLD_HOE:
			return "";
		case GOLD_INGOT:
			return "";
		case GOLD_LEGGINGS:
			return "";
		case GOLD_NUGGET:
			return "";
		case GOLD_ORE:
			return "";
		case GOLD_PICKAXE:
			return "";
		case GOLD_PLATE:
			return "";
		case GOLD_RECORD:
			return "";
		case GOLD_SPADE:
			return "";
		case GOLD_SWORD:
			return "";
		case GRASS:
			return "";
		case GRAVEL:
			return "";
		case GREEN_RECORD:
			return "";
		case GRILLED_PORK:
			return "";
		case HARD_CLAY:
			return "";
		case HAY_BLOCK:
			return "";
		case HOPPER:
			return "";
		case HOPPER_MINECART:
			return "";
		case HUGE_MUSHROOM_1:
			return "";
		case HUGE_MUSHROOM_2:
			return "";
		case ICE:
			return "";
		case INK_SACK:
			return "";
		case IRON_AXE:
			return "";
		case IRON_BARDING:
			return "";
		case IRON_BLOCK:
			return "";
		case IRON_BOOTS:
			return "";
		case IRON_CHESTPLATE:
			return "";
		case IRON_DOOR:
			return "";
		case IRON_DOOR_BLOCK:
			return "";
		case IRON_FENCE:
			return "";
		case IRON_HELMET:
			return "";
		case IRON_HOE:
			return "";
		case IRON_INGOT:
			return "";
		case IRON_LEGGINGS:
			return "";
		case IRON_ORE:
			return "";
		case IRON_PICKAXE:
			return "";
		case IRON_PLATE:
			return "";
		case IRON_SPADE:
			return "";
		case IRON_SWORD:
			return "";
		case IRON_TRAPDOOR:
			return "";
		case ITEM_FRAME:
			return "";
		case JACK_O_LANTERN:
			return "";
		case JUKEBOX:
			return "";
		case JUNGLE_DOOR:
			return "";
		case JUNGLE_DOOR_ITEM:
			return "";
		case JUNGLE_FENCE:
			return "";
		case JUNGLE_FENCE_GATE:
			return "";
		case JUNGLE_WOOD_STAIRS:
			return "";
		case LADDER:
			return "";
		case LAPIS_BLOCK:
			return "";
		case LAPIS_ORE:
			return "";
		case LAVA:
			return "";
		case LAVA_BUCKET:
			return "";
		case LEASH:
			return "";
		case LEATHER:
			return "";
		case LEATHER_BOOTS:
			return "";
		case LEATHER_CHESTPLATE:
			return "";
		case LEATHER_HELMET:
			return "";
		case LEATHER_LEGGINGS:
			return "";
		case LEAVES:
			return "";
		case LEAVES_2:
			return "";
		case LEVER:
			return "";
		case LOG:
			return "";
		case LOG_2:
			return "";
		case LONG_GRASS:
			return "";
		case MAGMA_CREAM:
			return "";
		case MAP:
			return "";
		case MELON:
			return "";
		case MELON_BLOCK:
			return "";
		case MELON_SEEDS:
			return "";
		case MELON_STEM:
			return "";
		case MILK_BUCKET:
			return "";
		case MINECART:
			return "";
		case MOB_SPAWNER:
			return "";
		case MONSTER_EGG:
			return "";
		case MONSTER_EGGS:
			return "";
		case MOSSY_COBBLESTONE:
			return "";
		case MUSHROOM_SOUP:
			return "";
		case MUTTON:
			return "";
		case MYCEL:
			return "";
		case NAME_TAG:
			return "";
		case NETHERRACK:
			return "";
		case NETHER_BRICK:
			return "";
		case NETHER_BRICK_ITEM:
			return "";
		case NETHER_BRICK_STAIRS:
			return "";
		case NETHER_FENCE:
			return "";
		case NETHER_STALK:
			return "";
		case NETHER_STAR:
			return "";
		case NETHER_WARTS:
			return "";
		case NOTE_BLOCK:
			return "";
		case OBSIDIAN:
			return "";
		case PACKED_ICE:
			return "";
		case PAINTING:
			return "";
		case PAPER:
			return "";
		case PISTON_BASE:
			return "";
		case PISTON_EXTENSION:
			return "";
		case PISTON_MOVING_PIECE:
			return "";
		case PISTON_STICKY_BASE:
			return "";
		case POISONOUS_POTATO:
			return "";
		case PORK:
			return "";
		case PORTAL:
			return "";
		case POTATO:
			return "";
		case POTATO_ITEM:
			return "";
		case POTION:
			return "";
		case POWERED_MINECART:
			return "";
		case POWERED_RAIL:
			return "";
		case PRISMARINE:
			return "";
		case PRISMARINE_CRYSTALS:
			return "";
		case PRISMARINE_SHARD:
			return "";
		case PUMPKIN:
			return "";
		case PUMPKIN_PIE:
			return "";
		case PUMPKIN_SEEDS:
			return "";
		case PUMPKIN_STEM:
			return "";
		case QUARTZ:
			return "";
		case QUARTZ_BLOCK:
			return "";
		case QUARTZ_ORE:
			return "";
		case QUARTZ_STAIRS:
			return "";
		case RABBIT:
			return "";
		case RABBIT_FOOT:
			return "";
		case RABBIT_HIDE:
			return "";
		case RABBIT_STEW:
			return "";
		case RAILS:
			return "";
		case RAW_BEEF:
			return "";
		case RAW_CHICKEN:
			return "";
		case RAW_FISH:
			return "";
		case RECORD_10:
			return "";
		case RECORD_11:
			return "";
		case RECORD_12:
			return "";
		case RECORD_3:
			return "";
		case RECORD_4:
			return "";
		case RECORD_5:
			return "";
		case RECORD_6:
			return "";
		case RECORD_7:
			return "";
		case RECORD_8:
			return "";
		case RECORD_9:
			return "";
		case REDSTONE:
			return "";
		case REDSTONE_BLOCK:
			return "";
		case REDSTONE_COMPARATOR:
			return "";
		case REDSTONE_COMPARATOR_OFF:
			return "";
		case REDSTONE_COMPARATOR_ON:
			return "";
		case REDSTONE_LAMP_OFF:
			return "";
		case REDSTONE_LAMP_ON:
			return "";
		case REDSTONE_ORE:
			return "";
		case REDSTONE_TORCH_OFF:
			return "";
		case REDSTONE_TORCH_ON:
			return "";
		case REDSTONE_WIRE:
			return "";
		case RED_MUSHROOM:
			return "";
		case RED_ROSE:
			return "";
		case RED_SANDSTONE:
			return "";
		case RED_SANDSTONE_STAIRS:
			return "";
		case ROTTEN_FLESH:
			return "";
		case SADDLE:
			return "";
		case SAND:
			return "";
		case SANDSTONE:
			return "";
		case SANDSTONE_STAIRS:
			return "";
		case SAPLING:
			return "";
		case SEA_LANTERN:
			return "";
		case SEEDS:
			return "";
		case SHEARS:
			return "";
		case SIGN:
			return "";
		case SIGN_POST:
			return "";
		case SKULL:
			return "";
		case SKULL_ITEM:
			return "";
		case SLIME_BALL:
			return "";
		case SLIME_BLOCK:
			return "";
		case SMOOTH_BRICK:
			return "";
		case SMOOTH_STAIRS:
			return "";
		case SNOW:
			return "";
		case SNOW_BALL:
			return "";
		case SNOW_BLOCK:
			return "";
		case SOIL:
			return "";
		case SOUL_SAND:
			return "";
		case SPECKLED_MELON:
			return "";
		case SPIDER_EYE:
			return "";
		case SPONGE:
			return "";
		case SPRUCE_DOOR:
			return "";
		case SPRUCE_DOOR_ITEM:
			return "";
		case SPRUCE_FENCE:
			return "";
		case SPRUCE_FENCE_GATE:
			return "";
		case SPRUCE_WOOD_STAIRS:
			return "";
		case STAINED_CLAY:
			return "";
		case STAINED_GLASS:
			return "";
		case STAINED_GLASS_PANE:
			return "";
		case STANDING_BANNER:
			return "";
		case STATIONARY_LAVA:
			return "";
		case STATIONARY_WATER:
			return "";
		case STEP:
			return "";
		case STICK:
			return "";
		case STONE:
			return "";
		case STONE_AXE:
			return "";
		case STONE_BUTTON:
			return "";
		case STONE_HOE:
			return "";
		case STONE_PICKAXE:
			return "";
		case STONE_PLATE:
			return "";
		case STONE_SLAB2:
			return "";
		case STONE_SPADE:
			return "";
		case STONE_SWORD:
			return "";
		case STORAGE_MINECART:
			return "";
		case STRING:
			return "";
		case SUGAR:
			return "";
		case SUGAR_CANE:
			return "";
		case SUGAR_CANE_BLOCK:
			return "";
		case SULPHUR:
			return "";
		case THIN_GLASS:
			return "";
		case TNT:
			return "";
		case TORCH:
			return "";
		case TRAPPED_CHEST:
			return "";
		case TRAP_DOOR:
			return "";
		case TRIPWIRE:
			return "";
		case TRIPWIRE_HOOK:
			return "";
		case VINE:
			return "";
		case WALL_BANNER:
			return "";
		case WALL_SIGN:
			return "";
		case WATCH:
			return "";
		case WATER:
			return "";
		case WATER_BUCKET:
			return "";
		case WATER_LILY:
			return "";
		case WEB:
			return "";
		case WHEAT:
			return "";
		case WOOD:
			return "";
		case WOODEN_DOOR:
			return "";
		case WOOD_AXE:
			return "";
		case WOOD_BUTTON:
			return "";
		case WOOD_DOOR:
			return "";
		case WOOD_DOUBLE_STEP:
			return "";
		case WOOD_HOE:
			return "";
		case WOOD_PICKAXE:
			return "";
		case WOOD_PLATE:
			return "";
		case WOOD_SPADE:
			return "";
		case WOOD_STAIRS:
			return "";
		case WOOD_STEP:
			return "";
		case WOOD_SWORD:
			return "";
		case WOOL:
			return "";
		case WORKBENCH:
			return "";
		case WRITTEN_BOOK:
			return "";
		case YELLOW_FLOWER:
			return "";
		default:
			return "";
		
		}
	}
	
}
